<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AplicacionExterna extends BaseAplicacionExterna
{
	public function __toString()
	{
		return $this->nombre;
	}
}