<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaIniciativa extends BaseCategoriaIniciativa
{

	public function __toString()
	{
		return $this->nombre;
	}
	
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public static function getArrayCategoria()
	{
		$categoria = CategoriaIniciativaTable::getAll();
		
		$arraycategoria = array('0'=>'--seleccionar--');
		
		foreach ($categoria as $c)
		{
			
			$arraycategoria[$c->getId()] = $c->getNombre();
			
		}
		
		return $arraycategoria;
	}
	
	
	
}