<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaDG extends BaseCategoriaDG
{
	public function __toString()
	{
		return $this->nombre;
	}
	
	public static function ArrayDECategorias()
	{
		$returArray = array();
		$arrayCat = CategoriaDGTable::getAllcategoria();
		foreach ($arrayCat AS $value )
		{
		   $id = $value->getId();
		   $returArray[$id] = $value->getNombre();
		   
		}
		
	  return	$returArray;
	}
	
}