<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComunicadoTable extends Doctrine_Table
{
	public static function getNoEnviados()
	{
		$q = Doctrine_Query::create();
		$q->from('Comunicado c');
		$q->where('c.deleted = 0');
		$q->andWhere('c.enviado = 0');
		$q->orderBy('c.nombre ASC');
		$comunicados = $q->execute();
		
		return $comunicados;
	}
	
}