<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListaComunicadoTable extends Doctrine_Table
{
	public function getListasActivas()
	{
		$q = Doctrine_Query::create();
		$q->from('ListaComunicado lc');
		$q->where('lc.deleted = 0');
		$q->orderBy('lc.nombre ASC');
		$listas = $q->execute();
		
		return $listas;
	}
	
}