<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaNormativaN2Table extends Doctrine_Table
{
   public static function getSubcategiriaBycategoria($id)
	{
	   $q = Doctrine_Query::create()
	   ->from('SubCategoriaNormativaN2')
	   ->where('subcategoria_normativa_id  = '.$id)
	   ->andWhere('deleted = 0');
	   
	   return $q->execute();
	   
	}  
	public static function getAll()
	{
	   $q = Doctrine_Query::create()
	   ->from('SubCategoriaNormativaN2')
	   ->andWhere('deleted = 0');
	   
	   return $q->execute();
	   
	}  
	
	
}