<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioAsamblea extends BaseUsuarioAsamblea
{
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public static function getUsuariosDirectores($idasmblea)
	{
		$objtDirectores = UsuarioAsambleaTable::getUsuByAsam($idasmblea);
		
		$arraResult = array();
		
		foreach ($objtDirectores as $o)
		{
			
			$arraResult[$o->getUsuarioId()] = $o->getUsuarioId();
		}
		
		
		return $arraResult;
		
	}
	
}