<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAsamblea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asamblea');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fecha_caducidad', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('horario', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('contenido', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('estado', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'activa',
              1 => 'anulada',
              2 => 'pendiente',
              3 => 'caducada',
             ),
             ));
        $this->hasColumn('entidad', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Usuario', array(
             'local' => 'owner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('UsuarioAsamblea as UsuarioEventos', array(
             'local' => 'id',
             'foreign' => 'asamblea_id'));

        $this->hasMany('Convocatoria', array(
             'local' => 'id',
             'foreign' => 'asamblea_id'));

        $this->hasMany('Acta', array(
             'local' => 'id',
             'foreign' => 'asamblea_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}