<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseContenido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contenido');
        $this->hasColumn('titulo', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('contenido', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('permalink', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}