<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMutua extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mutua');
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('detalle', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Usuario', array(
             'local' => 'id',
             'foreign' => 'mutua_id'));

        $this->hasMany('Noticia', array(
             'local' => 'id',
             'foreign' => 'mutua_id'));

        $this->hasMany('Publicacion', array(
             'local' => 'id',
             'foreign' => 'mutua_id'));

        $this->hasMany('Actividad', array(
             'local' => 'id',
             'foreign' => 'mutua_id'));

        $this->hasMany('CifraDato', array(
             'local' => 'id',
             'foreign' => 'mutua_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}