<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAplicacionAccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aplicacion_accion');
        $this->hasColumn('accion', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'alta',
              1 => 'baja',
              2 => 'modificar',
              3 => 'listar',
              4 => 'publicar',
             ),
             ));
        $this->hasColumn('accion_del_modulo', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('aplicacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Aplicacion', array(
             'local' => 'aplicacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}