<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseListaComunicado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lista_comunicado');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Usuario as Usuarios', array(
             'refClass' => 'UsuarioListaComunicado',
             'local' => 'lista_comunicado_id',
             'foreign' => 'usuario_id'));

        $this->hasMany('EnvioComunicado as EnviosComunicado', array(
             'refClass' => 'ListaComunicadoEnvio',
             'local' => 'lista_comunicado_id',
             'foreign' => 'envio_comunicado_id'));

        $this->hasMany('ListaComunicadoEnvio as ListaComunicadoEnvios', array(
             'local' => 'id',
             'foreign' => 'lista_comunicado_id'));

        $this->hasMany('UsuarioListaComunicado as UsuarioListasComunicado', array(
             'local' => 'id',
             'foreign' => 'lista_comunicado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}