<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseActa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acta');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('detalle', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('asamblea_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Asamblea', array(
             'local' => 'asamblea_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Usuario', array(
             'local' => 'owner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}