<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEnvioComunicado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('envio_comunicado');
        $this->hasColumn('comunicado_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tipo_comunicado_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Comunicado', array(
             'local' => 'comunicado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TipoComunicado', array(
             'local' => 'tipo_comunicado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ListaComunicado as ListaComunicados', array(
             'refClass' => 'ListaComunicadoEnvio',
             'local' => 'envio_comunicado_id',
             'foreign' => 'lista_comunicado_id'));

        $this->hasMany('ListaComunicadoEnvio as ListaComunicadoEnvios', array(
             'local' => 'id',
             'foreign' => 'envio_comunicado_id'));

        $this->hasMany('EnvioError', array(
             'local' => 'id',
             'foreign' => 'envio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}