<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseArchivoDO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo_d_o');
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_caducidad', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('contenido', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('archivo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('disponibilidad', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'organismo',
              1 => 'todos',
             ),
             ));
        $this->hasColumn('categoria_organismo_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subcategoria_organismo_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organismo_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('documentacion_organismo_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('CategoriaOrganismo', array(
             'local' => 'categoria_organismo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SubCategoriaOrganismo', array(
             'local' => 'subcategoria_organismo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Organismo', array(
             'local' => 'organismo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DocumentacionOrganismo', array(
             'local' => 'documentacion_organismo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}