<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNotificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notificacion');
        $this->hasColumn('estado', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'leido',
              1 => 'noleido',
             ),
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('contenido_notificacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('entidad_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('visto', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('ContenidoNotificacion', array(
             'local' => 'contenido_notificacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}