<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTipoComunicado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_comunicado');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EnvioComunicado', array(
             'local' => 'id',
             'foreign' => 'tipo_comunicado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}