<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAplicacionExterna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aplicacion_externa');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('detalle', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('imagen', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Usuario as Usuarios', array(
             'refClass' => 'UsuarioAplicacionExterna',
             'local' => 'aplicacion_externa_id',
             'foreign' => 'usuario_id'));

        $this->hasMany('UsuarioAplicacionExterna as UsuarioAplicacionExternas', array(
             'local' => 'id',
             'foreign' => 'aplicacion_externa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}