<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIniciativa extends Documentacion
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('iniciativa');
        $this->hasColumn('categoria_iniciativa_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subcategoria_iniciativa_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('documento', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('CategoriaIniciativa', array(
             'local' => 'categoria_iniciativa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SubCategoriaIniciativa', array(
             'local' => 'subcategoria_iniciativa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}