<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSubCategoriaIniciativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_categoria_iniciativa');
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('contenido', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('categoria_iniciativa_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('CategoriaIniciativa', array(
             'local' => 'categoria_iniciativa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Iniciativa', array(
             'local' => 'id',
             'foreign' => 'subcategoria_iniciativa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}