<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAplicacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aplicacion');
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('nombre_entidad', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('nombre_modulo', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('tipo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'front',
              1 => 'back',
             ),
             ));
        $this->hasColumn('titulo', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        $this->hasMany('AplicacionRol', array(
             'local' => 'id',
             'foreign' => 'aplicacion_id'));

        $this->hasMany('AplicacionAccion', array(
             'local' => 'id',
             'foreign' => 'aplicacion_id'));

        $this->hasMany('Menu', array(
             'local' => 'id',
             'foreign' => 'aplicacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}