<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseListaComunicadoEnvio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lista_comunicado_envio');
        $this->hasColumn('envio_comunicado_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('lista_comunicado_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        $this->hasOne('EnvioComunicado', array(
             'local' => 'envio_comunicado_id',
             'foreign' => 'id'));

        $this->hasOne('ListaComunicado', array(
             'local' => 'lista_comunicado_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}