<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUsuarioListaComunicado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_lista_comunicado');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('lista_comunicado_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        $this->hasOne('ListaComunicado', array(
             'local' => 'lista_comunicado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}