<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNovedad extends Noticia
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('novedad');
    }

    public function setUp()
    {
        parent::setUp();
    $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}