<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCategoriaNormativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria_normativa');
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('contenido', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Normativa', array(
             'local' => 'id',
             'foreign' => 'categoria_normativa_id'));

        $this->hasMany('SubCategoriaNormativaN1', array(
             'local' => 'id',
             'foreign' => 'categoria_normativa_id'));

        $this->hasMany('SubCategoriaNormativaN2', array(
             'local' => 'id',
             'foreign' => 'categoria_normativa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}