<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCircularSubTema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('circular_sub_tema');
        $this->hasColumn('nombre', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('circular_cat_tema_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        $this->hasOne('CircularCatTema', array(
             'local' => 'circular_cat_tema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Circular', array(
             'local' => 'id',
             'foreign' => 'circular_sub_tema_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}