<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accion');
        $this->hasColumn('entidad_creadora', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Noticia',
              1 => 'Evento',
              2 => 'Asamblea',
             ),
             ));
        $this->hasColumn('entidad_creadora_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('entidad', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Publico',
              1 => 'GrupoTrabajo',
              2 => 'ConsejoTerritorial',
              3 => 'Organismo',
             ),
             ));
        $this->hasColumn('entidad_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('accion', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'ver',
             ),
             ));
    }

    public function setUp()
    {
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}