<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActaTable extends Doctrine_Table
{
   public static function getActasByAsamblea($idAsamblea,$idUsuer)
   {
   	  $q=Doctrine_Query::create()
   	  ->from('Acta')
   	  ->where('asamblea_id ='.$idAsamblea)
   	  ->andWhere('owner_id ='.$idUsuer);
   	  
   	  return $q->fetchOne();
   	
   }
	
}