<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaCTTable extends Doctrine_Table
{
 static function getAllcategoriasCT()
	{
		$q = Doctrine_Query::create()->from('CategoriaCT');
		$retorno = $q->execute();
		
		return $retorno;
	}
 public static function getCategoriasCT($id)
   {
   	 $r = Doctrine_Query::create()
   	 ->from('CategoriaCT')
   	 ->where('id = '.$id);
   	 $respuesat = $r->fetchOne();
   	 
   	 return $respuesat;
   }
	
}