<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioConsejoTerritorialTable extends Doctrine_Table
{
   public static function getUsreByConse($id)
	{
		$q=Doctrine_Query::create()
		->from('UsuarioConsejoTerritorial uc')
		->leftJoin('uc.Usuario u')
		->leftJoin('uc.ConsejoTerritorial ct')
		->where('uc.consejo_territorial_id  ='.$id);
		
		return $q->execute();
	}
	
	
}