<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcuerdoTable extends DocumentacionTable
{

    public static function getFechasCategorias()
	{
		$r = Doctrine_Query::create()
		->select('MIN(YEAR(fecha)) AS min_year, MAX(YEAR(fecha)) AS max_year')
		->from('Acuerdo')->where('deleted = 0');

		return $r->fetchOne();
	}

   public static function getAcuerdosBycategoria($id)
       {
           $q=Doctrine_Query::create()
           ->from('Acuerdo')
           ->where('categoria_acuerdo_id = '.$id)
           ->andWhere('deleted = 0');


           return $q->execute();

       }
    public static function getAcuerdosBySubcategoria($id)
       {
           $q=Doctrine_Query::create()
           ->from('Acuerdo')
           ->where('subcategoria_acuerdo_id = '.$id)
           ->andWhere('deleted = 0');


           return $q->execute();

       }
    public static function getAll()
       {
            $q=Doctrine_Query::create()
           ->from('Acuerdo')
           ->where('deleted = 0');

           return $q->execute();

       }
}