<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgendaTable extends Doctrine_Table
{

	public static function getEventoByUsuario($evento='',$convocatoria='',$usuario)
	{
		$q = Doctrine_Query::create()
		->from('Agenda')
		->where('deleted = 0')
		->addWhere('usuario_id = '.$usuario);
		if($evento!='')
		{
		 $q->addWhere('evento_id = '.$evento);
		} 
		if($convocatoria!='')
		{
		 $q->addWhere('convocatoria_id  = '.$convocatoria);
		} 
		
		return $q->execute();
	}
	
}