<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgendaTable extends Doctrine_Table
{

	public static function getEventoByUsuario($evento='',$convocatoria='',$usuario='')
	{
		$q = Doctrine_Query::create()
		->from('Agenda')
		->where('deleted = 0');
                $q->addWhere('usuario_id = '.$usuario.' OR publico = 1');
		if($evento!='')
		{
		 $q->addWhere('evento_id = '.$evento);
		} 
		if($convocatoria!='')
		{
		 $q->addWhere('convocatoria_id  = '.$convocatoria);
		}
		$q->groupBy('url');
		return $q->execute();
	}
	
	public static function getDeleteAgenda($idEntidad)
	{
		$q = Doctrine_Query::create()
		     ->from('Agenda')
		     ->where('evento_id = '.$idEntidad);
		     
		 return $q->execute();    	
	}
	
	public static function getDeleteAgenda2($idEntidad)
	{
		$q = Doctrine_Query::create()
			 ->delete()
		     ->from('Agenda')
		     ->where('evento_id IN '.$idEntidad);
		     
		 return $q->execute();    	
	}
	
	
}