<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AplicacionRolTable extends Doctrine_Table
{
   public static function getAplicacionRol($id)
   {
   	 $r = Doctrine_Query::create()
   	 ->from('Aplicacion')
   	 ->where('id = '.$id);
   	 $respuesat = $r->fetchOne();
   	 
   	 return $respuesat;
   }
   
   
   public static function getEmailPublicar($IDaplic)
   {
   	 $r=Doctrine_Query::create()
   	    ->from('Usuario u')
   	    ->leftJoin('u.UsuarioRol ur')
   	    ->leftJoin('ur.Rol r')
   	    ->leftJoin('r.AplicacionRol ar')
   	    ->where('ar.accion_publicar = 1')
   	    ->andWhere('ar.aplicacion_id = '.$IDaplic)
   	    ->andWhere('u.deleted = 0');
   	   
   	  return $r->execute();   
   }
   
   public static function getAplicacionByRol($idrol)
   {
   	 $r=Doctrine_Query::create()
   	    ->from('AplicacionRol ar')
   	    ->leftJoin('ar.Aplicacion a')
   	    ->andWhere('ar.rol_id = '.$idrol)
   	    ->andWhere('a.deleted = 0 AND ar.deleted = 0')
   	    ->andWhere('a.id != 44 AND a.id != 46')
   	    ->orderBy('a.nombre');
   	   
   	  return $r->execute();   
   }
   
   
   
}