<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Aplicacion extends BaseAplicacion
{
	public function __toString()
	{
		return $this->nombre;
	}
	
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	
	public static function getArrayAplicacion()
	{
		$ArrayAplicacion = array();
		$ModelosAplicacion = AplicacionTable::getAplicacion();
		
//		echo '<pre>';
//		print_r($ModelosAplicacion);
//		echo '</pre>';
//		exit();
		
		foreach ($ModelosAplicacion AS $m)
		{
			$ArrayAplicacion[$m->getId()] = $m->getNombre();
		}
		
		return $ArrayAplicacion;
	}
	
}