<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CifraDato extends BaseCifraDato
{
	public function eliminarImagen(){
		@unlink(sfConfig::get('sf_upload_dir').'/cifras_datos/images/'.$this->getImagen());
	    @unlink(sfConfig::get('sf_upload_dir').'/cifras_datos/images/'.'s_'.$this->getImagen());
	}
	
	public function eliminarDocumento(){
		@unlink(sfConfig::get('sf_upload_dir').'/cifras_datos/docs/'.$this->getDocumento());
	}
	
	 public function save(Doctrine_Connection $conn = null)
  {        
  	
 								$request  = sfContext::getInstance()->getRequest();
                $stAction = $request->getParameter('action'); 	
                $userid = sfContext::getInstance()->getUser()->getAttribute('userId'); 	
                if ($this->isNew())
                {
                        $this->setUserIdCreador($userid);
                }
                else 
                {
                	      $this->setUserIdModificado($userid) ;
                	
                }
                if($stAction == 'publicar') 
                
                {
                	       $this->setUserIdPublicado($userid);
                	       $this->setFechaPublicado(date('Y-m-d H:i:s'));
                }
                                
                return parent::save($conn);
    }
	
	
}