<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentacionGrupoTable extends DocumentacionTable
{
	public static function doSelectByGrupoTrabajo($grupo_trabajo, $combo='', $user= '')
	{
		if (empty($grupo_trabajo)) {return false;}
    
		$q = Doctrine_Query::create();

		$q->from('DocumentacionGrupo');
		$q->where('deleted = 0');
		$q->addWhere('grupo_trabajo_id = ' . $grupo_trabajo);
                if($user!= ''){
                $q->addWhere("owner_id = ".$user." OR estado != 'guardado'");
                }
		$q->orderBy('nombre ASC');
		$documentacion = $q->execute();
    
		return $documentacion;
	}
	
	public static function getAlldocumentos($user= '')
	{
		$s = Doctrine_Query::create();
		$s->from('DocumentacionGrupo');
		$s->where('deleted = 0');
                if($user!= ''){
                $s->addWhere("owner_id = ".$user." OR estado != 'guardado'");
                }

		$retorno = $s->execute();
		
		return $retorno;
	}
	public static function getDocumentacionGrupoTrabajo($id)
   {
   	 $r = Doctrine_Query::create()
   	 ->from('DocumentacionGrupo')
   	 ->where('id = '.$id);
   	 $respuesat = $r->fetchOne();
   	 
   	 return $respuesat;
   }
}