<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnvioError extends BaseEnvioError
{
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public static function saveEnvioerror($id_envio, $id_usuario, $error)
	{
		$EnvioErro = new EnvioError();
		$EnvioErro->setEnvioId($id_envio);
		$EnvioErro->setUsuarioId($id_usuario);
		$EnvioErro->setError($error);
		$EnvioErro->setEstado(0);
		$EnvioErro->save();
		
		return true;
	}
}