<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IniciativaTable extends DocumentacionTable
{

	public static function getFechasCategorias()
	{
		$r = Doctrine_Query::create()
		->select('MIN(YEAR(fecha)) AS min_year, MAX(YEAR(fecha)) AS max_year')
		->from('Iniciativa')->where('deleted = 0');
		

		return $r->fetchOne();
	}
	
	
}