<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuTable extends Doctrine_Table
{
	public static function getGrupo()
	{
		$e=Doctrine_Query::create()
		->from('Menu')
		->where('deleted = 0')
	  	->addWhere('padre_id = 0');
	  	$menugrupo = $e->execute();
	
		return $menugrupo;
	}
	
	public static function getMenuPadre($idPadre, $habilitado = null)
	{
		$s = Doctrine_Query::create()
		->from('Menu')
		->where('deleted = 0')
		->addWhere('padre_id = '.$idPadre)
		->orderBy('posicion');
		if ($habilitado == 1)
		{
			$s->addWhere('habilitado = 1');
		}
		$menupadre = $s->execute();
		
		return $menupadre;
	}
	
	public static function getIdpadre($id_menu)
	{
		$s=Doctrine_Query::create()
		->from('Menu')
		->where('id ='.$id_menu);
		$IdPadre = $s->fetchOne();
	
		return $IdPadre; 
	}
	
	public static function getExistPosicion($posicion,$id_padre)
	{
		$d = Doctrine_Query::create()
		->from('Menu')
		->where('padre_id ='.$id_padre)
		->addwhere('posicion ='.$posicion);
		$retorno = $d->fetchOne();
				
		return $retorno;  
	}
	
	public static function getPosiscionIgualMayor($posicion,$id_padre)
	{
		$g = Doctrine_Query::create()
		->from('Menu')
		->where('padre_id ='.$id_padre)
		->addwhere('posicion >='.$posicion);
		$retornoPosiciones = $g->execute();

		return $retornoPosiciones;
	}
	
	public static function getPosiscionIgual($posicion,$id_padre)
	{
		$g = Doctrine_Query::create()
		->from('Menu')
		->where('padre_id ='.$id_padre)
		->addwhere('posicion ='.$posicion);
		$retornoPosicion = $g->fetchOne();

		return $retornoPosicion;
	}
	
	public static function getArrayMenuHijo($idPadre, $nivel)
	{
                sfLoader::loadHelpers('Security');
		$items = MenuTable::getMenuPadre($idPadre,1);
		$arrItems = array();
		
		//echo "<br /> nivel: ".$nivel;
		
		if (count($items)!=0 && $nivel <= 3)
		{
			foreach($items as $item)
			{   
				$asambleas = '';
				$aplicacion ='';
				if($item->getAplicacion()->getId() == 4)
			      {
			      	$aplicacion = $item->getAplicacion()->getNombreModulo().'/index?DirectoresGerente=1';
			      	$asambleas = 1;
			      }
			     if($item->getAplicacion()->getId() == 42)
			      {
			      	$aplicacion = $item->getAplicacion()->getNombreModulo().'/index?GrupodeTrabajo=2';
			      	$asambleas = 2;
			      } 
			      if($item->getAplicacion()->getId() == 43)
			      {
			      	$aplicacion = $item->getAplicacion()->getNombreModulo().'/index?ConsejoTerritorial=3';
			      	$asambleas = 3;
			      }
			      if($item->getAplicacion()->getId() != 4 && $item->getAplicacion()->getId() != 42 && $item->getAplicacion()->getId() != 43)
			      {
			      	if($item->getAplicacion()->getNombreModulo()){
			      	$aplicacion = $item->getAplicacion()->getNombreModulo().'/index';
			      	}
			      	$asambleas = '';
			      }
			      if($item->getAplicacion()->getTitulo() != '' && $item->getAplicacion()->getDescripcion() != '')
			      {
			      	
			      	$aplicacion = $item->getAplicacion()->getNombreModulo().'/show?id='.$item->getAplicacion()->getId();
			      	
			      }
                              if($item->getAplicacion()->getId() != 51 && !validate_action('alta', $item->getAplicacion()->getNombreModulo()))
                              {
                                  $arrItems [  ] = array (
					'id' 		=> $item->getId(),
					'nombre' 	=> $item->getNombre(),
					'modulo' 	=> $item->getAplicacion()->getNombreModulo(),
					'url' 		=> $item->getUrlExterna(),
					'asambleas' => $asambleas,
					'aplicacion'=> $aplicacion,
					'hijos'		=> MenuTable::getArrayMenuHijo($item->getId(), $nivel + 1),
					);

                              }
			      else 
                              {
                                  $arrItems [  ] = array ( 
					'id' 		=> $item->getId(), 
					'nombre' 	=> $item->getNombre(), 
					'modulo' 	=> $item->getAplicacion()->getNombreModulo(), 
					'url' 		=> $item->getUrlExterna(),
					'asambleas' => $asambleas,
					'aplicacion'=> $aplicacion,
					'hijos'		=> MenuTable::getArrayMenuHijo($item->getId(), $nivel + 1), 
					);
                                  
                              }
				
			}						
		}
	 
		return $arrItems;
	}
}