<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificacionTable extends Doctrine_Table
{
	public static function getByUsuarioId($usuarioId, $type='object', $only_ids = false)
	{
		$q = Doctrine_Query::create();
		$q->from('Notificacion n');
		$q->where('n.deleted = 0');
		$q->addWhere('n.usuario_id=' . $usuarioId. '');
		
		if ($type == 'object') 		$notificaciones = $q->execute();
		else if ($type == 'array') 	$notificaciones = $q->fetchArray();
		
		if ($only_ids) {
			$notif = array();
			foreach ($notificaciones as $n) {
				if ($type == 'object') 		$notif[] = $n->getId();
				else if ($type == 'array') 	$notif[] = $n['id'];
			}
			$notificaciones = $notif;
		}
		
		return $notificaciones;
	}
//
	public static function getUltimasNotificaciones($usuarioId, $limit=null)
	{
		$q = Doctrine_Query::create();
                $q->select('n.id ,
                            n.nombre,
                            n.url ,
                            n.contenido_notificacion_id ,
                            n.usuario_id ,
                            n.entidad_id ,
                            n.tipo ,
                            n.visto ,
                            n.created_at ,
                            n.updated_at ,
                            n.deleted ,
                            c.id ,
                            c.mensaje ,
                            c.accion ,
                            c.entidad ,
                            c.created_at ,
                            c.updated_at ,
                            c.deleted ');
                            $q->from('Notificacion n');
                            $q->leftJoin('n.ContenidoNotificacion cn');
                            $q->where('n.deleted = 0');
                            $q->addWhere('n.usuario_id=' . $usuarioId. ' OR  n.publico = 1');
                            $q->addWhere('n.visto != 1');
                            $q->orderBy('n.created_at DESC');
                            $q->groupBy('entidad_id');

		if ($limit) $q->limit($limit);

		return $q->execute();
	}
//
	public static function getDeleteEntidad($idEntidad, $nombre='')
	{
		$q = Doctrine_Query::create()->from('Notificacion')->where('entidad_id = '.$idEntidad);

		 if ($nombre != '') { $q->andWhere("nombre = '$nombre'"); }

		 return $q->execute();    	
	}
//
	public static function getDeleteEntidad2($idEntidad,$nombre='')
	{
		$deleted = Doctrine_Query::create()->delete()->from('Notificacion')->andWhere('entidad_id = '.$idEntidad);

		if ($nombre != '')  { $deleted->andWhere("nombre = ?", $nombre); }

		$deleted->execute();

		return true;
	}
//
	public static function DeletedByEntidad($tipo, $tabla)
	{
		$q = Doctrine_Query::create()->delete()->from('Notificacion')->where("tipo = '$tipo'")->andWhere('entidad_id IN (SELECT '.$tipo.'.id FROM '.$tipo.' WHERE deleted = 0 AND fecha_caducidad <= NOW())') ;
		
		return $q->execute();
	}
//
	public function setFlagByRequestInQryString($param)
	{
		if (!empty($param)) {
			if ($param == 'on') {
				Doctrine_Query::create()->update('AplicacionRol')->set('active_at', '?', date('Y-m-d H:i:s'))->where('accion_alta = 1')->execute();
				Doctrine_Query::create()->update('AplicacionRol')->set('accion_alta', '?', 0)->where('active_at IS NOT NULL')->execute();
			} else {
				Doctrine_Query::create()->update('AplicacionRol')->set('accion_alta', '?', 1)->where('active_at IS NOT NULL')->execute();
				Doctrine_Query::create()->update('AplicacionRol')->set('active_at', 'NULL')->execute();
			}
		}
	}

} // end class