<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Notificacion extends BaseNotificacion
{
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

} // end class