<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Organismo extends BaseOrganismo
{
	public function __toString()
	{
		return $this->nombre;
	}
	public function getUsusriosMiOrganismo($usuarioId)
	{
		$s = Doctrine_Query::create();
		$s->select('u.*');
		$s->from('Usuario u');
		$s->leftJoin('u.UsuarioOrganismo uo');
		$s->where('uo.organismo_id = '.$this->getId() );
		$s->andWhere('u.id != '.$usuarioId);
		
		$usuarios = $s->execute();
		
		return $usuarios;
	}
	public static  function IdDeOrganismo($id_usuario,$misuser='')
	{
		$consejos = OrganismoTable::getOrganismoBysuer($id_usuario);
		
		if(count($consejos)>0)
		{
			if($misuser=='')
			{
				$armado =" AND am.entidad IN (";
				$base = 'Organismo_';
			}	
			else 
			{
				$armado ="(";
				$base = '';
			}
			$rt = 0;
			foreach ( $consejos AS $gruposid )
			{ 
				$rt++;
				if($rt != count($consejos))
				{
				  $armado .= "'".$base.$gruposid->getId()."',";
				}
				else 
				{
				  $armado .= "'".$base.$gruposid->getId()."')";
				}
				
				
			}
		}
		else 
		{
			$armado='';
		}
		
	   return 	$armado;
	}
}