<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolTable extends Doctrine_Table
{
   public static function getRol($id)
   {
   	 $r = Doctrine_Query::create()
   	 ->from('Rol')
   	 ->where('id = '.$id);
   	 $respuesat = $r->fetchOne();
   	 
   	 return $respuesat;
   }
	
   public static function getAllRol($name = '')
   {
   	 $r=Doctrine_Query::create()
   	 ->from('Rol')
   	 ->where('deleted = 0')
   	 ->orderBy('nombre');

         if($name!=''){
           $r->addWhere("nombre = '$name'");
           $r->addWhere("excepcion = 1");
         }else{
           $r->addWhere("excepcion = 0");
         }
   	 
   	 return $r->execute();
   	    	 
   } 
	 
}