<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaNormativaN1Table extends Doctrine_Table
{
	public static function getSubcategiriaBycategoria($id)
	{
	   $q = Doctrine_Query::create()
	   ->from('SubCategoriaNormativaN1')
	   ->where('categoria_normativa_id  = '.$id)
	   ->andWhere('deleted = 0');
	   
	   return $q->execute();
	   
	}  
	
	public static function getAll()
	{
	   $q = Doctrine_Query::create()
	   ->from('SubCategoriaNormativaN1')
	   ->andWhere('deleted = 0');
	   
	   return $q->execute();
	   
	}

        public static function getSubcategoriaById($id)
	{
	   $q = Doctrine_Query::create()
	   ->from('SubCategoriaNormativaN1')
	   ->where('deleted = 0')
           ->andWhere('id = '.$id)        ;


	   return $q->fetchOne();

	}
	
	
}