<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaNormativaN1 extends BaseSubCategoriaNormativaN1
{
    public function __toString()
	{
		return $this->nombre;
	}
	
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public static function getArraySubCategoria($id = '')
	{
		if($id!= '')
		{
		  $subcategoria = SubCategoriaNormativaN1Table::getSubcategiriaBycategoria($id);
		}
		else 
		{
		  $subcategoria = SubCategoriaNormativaN1Table::getAll();	
		}
		
		$arraysubcategoria = array('0'=>'--seleccionar--');
		
		foreach ($subcategoria as $c)
		{
			
			$arraysubcategoria[$c->getId()] = $c->getNombre();
			
		}
		
		return $arraysubcategoria;
	}
	
}