<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoComunicadoTable extends Doctrine_Table
{
	public static function AllTiposComunicados()
	{
		$s = Doctrine_Query::create()->from('TipoComunicado')->where('deleted = 0');
		$consulta = $s->execute();
		return $consulta;
	}

}