<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioRolTable extends Doctrine_Table
{
	public static function getRolesByUser( $user,$tipo='' )
	{
		$q = Doctrine_Query::create();
		$q->from('Rol r');
		$q->leftJoin('r.UsuarioRol ur');
		if($tipo=='')
		{
			$q->where('ur.usuario_id = ' . $user->getId());		
		    $roles = $q->execute();
			$strRoles ='';
			    
			    foreach ( $roles as $rol )
			    {
			    	$strRoles .= $rol.', ';
			    }	    
			
			return $strRoles ; 	
		}
		else 
		{
		  $q->where('ur.usuario_id ='.$user);		
		  $roles = $q->execute();
		  $strRoles = array();
			    
			    foreach ( $roles as $rol )
			    {
			    	$id =$rol->getId();
			    	$strRoles[$id] = $rol->getNombre();
			    }	    
			
			return $strRoles ; 	
		 		  	
		}
		
	}
	
	public static function getUserByRol($idRol, $userEx = '')
	{
		$q = Doctrine_Query::create()
		->from('UsuarioRol ur')
		->leftJoin('ur.Usuario u')
		->where('ur.rol_id = '.$idRol);
		if($userEx!='')
		{
			$q->addWhere('u.id NOT IN ('.$userEx.')');
		}
		
//		echo $q->getQuery();
//		exit();
		
		
		return $q->execute();
	}
	
}