<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioGrupoTrabajoTable extends Doctrine_Table
{
	public static function getUsreByGrupo($id,$conbocatoria = '')
	{
		$q=Doctrine_Query::create()
		->from('UsuarioGrupoTrabajo ug')
		->leftJoin('ug.Usuario u')
		->where('ug.grupo_trabajo_id ='.$id)
                ->andWhere('ug.deleted = 0')
                ->andWhere('u.deleted = 0 AND u.activo = 1');
               if($conbocatoria!=''){
                $q->leftJoin('ug.GrupoTrabajo g')
                  ->leftJoin('u.UsuarioRol ur')
                  ->andWhere('ur.rol_id IN (4,6)')
                  ->groupBy('u.id');
               }
		return $q->execute();
	}
	

}