<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioAsambleaTable extends Doctrine_Table
{
   public static function getUsuByAsam($id)
   {
   	  $q = Doctrine_Query::create()
   	  ->from('UsuarioAsamblea ua')
          ->leftJoin('ua.Usuario u')
   	  ->where('ua.asamblea_id = '.$id)
          ->andWhere('u.deleted = 0 AND u.activo = 1');

   	  return $q->execute();
   }
   	
   public static function getIdByUsu($id,$idUsu)
   {
   	  $q = Doctrine_Query::create()
   	  ->from('UsuarioAsamblea ua')
   	  ->where('ua.usuario_id = '.$id)
   	  ->andWhere('ua.asamblea_id = '.$idUsu);
   	  return $q->fetchOne();
   }
	
}