# default values

all:
  default_name_project: Extranet de Asociados AMAT
  default_from_email: info@intranet.amat.es
  
  # thumbnail default por si no se define el tamanio abajo
  thumbnail_normal_width_default:  400
  thumbnail_normal_height_default: 400

  # thumbnail cifras y datos
  thumbnail_small_width_cifras_datos:   100
  thumbnail_small_height_cifras_datos:  100
  thumbnail_normal_width_cifras_datos:  400
  thumbnail_normal_height_cifras_datos: 400

  # thumbnail actividades
  thumbnail_small_width_actividades:   100
  thumbnail_small_height_actividades:  100
  thumbnail_normal_width_actividades:  400
  thumbnail_normal_height_actividades: 400

  # thumbnail publicaciones
  thumbnail_small_width_publicaciones:   100
  thumbnail_small_height_publicaciones:  100
  thumbnail_normal_width_publicaciones:  400
  thumbnail_normal_height_publicaciones: 400
  
  # thumbnail noticias
  thumbnail_small_width_noticias:   80
  thumbnail_small_height_noticias:  40
  thumbnail_normal_width_noticias:  400
  thumbnail_normal_height_noticias: 400

  # thumbnail eventos
  thumbnail_normal_width_eventos:  200
  thumbnail_normal_height_eventos: 200
  thumbnail_small_width_eventos:   100
  thumbnail_small_height_eventos:  100

  # thumbnail Tipos Comunicados
  thumbnail_small_width_tipo_comunicado:   300
  thumbnail_small_height_tipo_comunicado:  26
  thumbnail_normal_width_tipo_comunicado:  800
  thumbnail_normal_height_tipo_comunicado: 80
