# default values

all:
  default_name_project: Extranet de Asociados AMAT
  default_from_email: info@intranet.amat.es
  
  # thumbnail default por si no se define el tamanio abajo
  thumbnail_normal_width_default:  250
  thumbnail_normal_height_default: 320

  # thumbnail cifras y datos
  thumbnail_web_original_width_cifras_datos:   250
  thumbnail_web_original_height_cifras_datos:  150
  thumbnail_web_small_width_cifras_datos:   120
  thumbnail_web_small_height_cifras_datos:  90
  thumbnail_web_width_cifras_datos:   315
  thumbnail_web_height_cifras_datos:  386
  thumbnail_small_width_cifras_datos:   80
  thumbnail_small_height_cifras_datos:  60
  thumbnail_normal_width_cifras_datos:  250
  thumbnail_normal_height_cifras_datos: 320

  # thumbnail actividades
  thumbnail_web_original_width_actividades:   250
  thumbnail_web_original_height_actividades:  150
  thumbnail_web_small_width_actividades:   120
  thumbnail_web_small_height_actividades:  90
  thumbnail_web_width_actividades:   315
  thumbnail_web_height_actividades:  386
  thumbnail_small_width_actividades:   80
  thumbnail_small_height_actividades:  60
  thumbnail_normal_width_actividades:  250
  thumbnail_normal_height_actividades: 320

  # thumbnail publicaciones
  thumbnail_web_original_width_publicaciones:   250
  thumbnail_web_original_height_publicaciones:  150
  thumbnail_web_small_width_publicaciones:   120
  thumbnail_web_small_height_publicaciones:  90
  thumbnail_web_width_publicaciones:   315
  thumbnail_web_height_publicaciones:  386
  thumbnail_small_width_publicaciones:   80
  thumbnail_small_height_publicaciones:  60
  thumbnail_normal_width_publicaciones:  250
  thumbnail_normal_height_publicaciones: 320
  
  # thumbnail noticias
  thumbnail_web_small_width_noticias:   120
  thumbnail_web_small_height_noticias:  90
  thumbnail_web_width_noticias:   315
  thumbnail_web_height_noticias:  386
  thumbnail_web_original_width_noticias:   510
  thumbnail_web_original_height_noticias:  600
  thumbnail_small_width_noticias:   80
  thumbnail_small_height_noticias:  60
  thumbnail_normal_width_noticias:  250
  thumbnail_normal_height_noticias: 320

  # thumbnail eventos
  thumbnail_normal_width_eventos:  250
  thumbnail_normal_height_eventos: 320
  thumbnail_small_width_eventos:   100
  thumbnail_small_height_eventos:  100

  # thumbnail Tipos Comunicados
  thumbnail_small_width_tipo_comunicado:   300
  thumbnail_small_height_tipo_comunicado:  26
  thumbnail_normal_width_tipo_comunicado:  800
  thumbnail_normal_height_tipo_comunicado: 80
