<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSolicitudClave extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('solicitud_clave');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}