<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAplicacionRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aplicacion_rol');
        $this->hasColumn('accion_alta', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('accion_baja', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('accion_modificar', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('accion_listar', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('accion_publicar', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('aplicacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rol_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Aplicacion', array(
             'local' => 'aplicacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Rol', array(
             'local' => 'rol_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}