<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNormasDeFuncionamiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('normas_de_funcionamiento');
        $this->hasColumn('titulo', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('grupo_trabajo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        $this->hasOne('GrupoTrabajo', array(
             'local' => 'grupo_trabajo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}