<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoDGTable extends Doctrine_Table
{
	public static function doSelectAllCategorias($tabla)
	{
		$q = Doctrine_Query::create();

		$q->from($tabla);
		$q->where('deleted = 0');
		$q->orderBy('nombre ASC');

		$categorias = $q->execute();

		return $categorias;
	}
	
	public static function getAllByDocumentacion($id)
	{
		$q = Doctrine_Query::create()
		->from('ArchivoDG')
		->where('documentacion_grupo_id = '.$id)
		->addWhere('deleted = 0');
		
		return $q->execute();
	}
	
	
}