<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Asamblea extends BaseAsamblea
{
	public function __toString()
	{
		return $this->titulo;
	}
	
	public function getUsuarios ()
	{
		## Obtener Entidad
		$aux = explode('_', $this->getEntidad());
		$entidad = $aux[0];
		$entidadId = $aux[1];
		
		## Obtener los usuarios de ese grupo
		if ($entidad == 'GrupoTrabajo') $usuarios = UsuarioTable::getUsuariosByGrupoTrabajo($entidadId);
		if ($entidad == 'ConsejoTerritorial') $usuarios = UsuarioTable::getUsuariosByConsejoTerritorial($entidadId);
		if ($entidad == 'Rol') $usuarios = UsuarioTable::getUsuariosByConsejosTerritoriales($entidadId);
		
		return $usuarios;
	}
}