<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CircularCatTemaTable extends Doctrine_Table
{
  public static function getAllCircularCat()
  {
  	$s = Doctrine_Query::create()
  	->from('CircularCatTema')
  	->where('deleted = 0');
  	$categoria = $s->execute();
  	
  	return $categoria;  
  }
	
	public static function getCircularCat($id)
   {
   	 $r = Doctrine_Query::create()
   	 ->from('CircularCatTema')
   	 ->where('id = '.$id);
   	 $respuesat = $r->fetchOne();
   	 
   	 return $respuesat;
   }
}