<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CircularCatTema extends BaseCircularCatTema
{
	public function __toString()
	{
		return $this->nombre;
	}
	
	public static function ArrayCirculares()
	{
		$arrayCircular = array();
		$circular = CircularCatTemaTable::getAllCircularCat();
		foreach ($circular AS $allCircular)
		{
			$idCircular = $allCircular['id'];
			$arrayCircular[$idCircular] = $allCircular['nombre'];
		}
		
		return $arrayCircular;
	}
}
