<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentacionConsejoTable extends DocumentacionTable
{
  public static function DocumentacionByConsejo($id_consejo,$combo = '', $user= '')
  {
  	$q = Doctrine_Query::create();
  	$q ->select('*');
  	$q ->from('DocumentacionConsejo');
  	$q->where('consejo_territorial_id='.$id_consejo);
        if($user!= ''){
        $q->addWhere("owner_id = ".$user." OR estado != 'guardado'");
        }
  	$q->andWhere('deleted = 0');
  	$consulta = $q->execute();
  	return $consulta;
  }
  
  public static function getAlldocumentacionC($user= '')
  {
  	$s=Doctrine_Query::create();
  	$s->from('DocumentacionConsejo');
  	$s->where('deleted = 0');
         if($user!= ''){
        $q->addWhere("owner_id = ".$user." OR estado != 'guardado'");
        }
  	$respuesta = $s->execute();
  	return $respuesta; 
  }
  public static function getDocumentacionConsejo($id)
   {
   	 $r = Doctrine_Query::create()
   	 ->from('DocumentacionConsejo')
   	 ->where('id = '.$id);
   	 $respuesat = $r->fetchOne();
   	 
   	 return $respuesat;
   }
}