<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Envios extends BaseEnvios
{

	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public static function saveEnvios($idenvios, $idusuario, $idmessage)
	{
		$envios = new Envios;
		$envios->setEnvioId($idenvios);
		$envios->setUsuarioId($idusuario);
		$envios->setMessageId($idmessage);
		$envios->save();	
		
		return true;
	}
	
	
}