<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnvioErrorTable extends Doctrine_Table
{

	public static function getEmailError($id)
	{
		$q=Doctrine_Query::create()
		->from('EnvioError er')
		->leftJoin('er.EnvioComunicado ec')
		->leftJoin('ec.Comunicado c')
		->leftJoin('er.Usuario u')
		->where('er.id = '.$id);
		
		return $q->fetchOne();
		
	}
}