<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Rol extends BaseRol
{
	public function __toString()
	{
		return $this->nombre;
	}
	
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	
	public static function getArrayRol()
	{
		$Arrayrol = array();
		$Modelosrol = RolTable::getAllRol();
		
		foreach ($Modelosrol AS $m)
		{
			$Arrayrol[$m->getId()] = $m->getNombre();
		}
		
		return $Arrayrol;
	}
	
	
}