<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioRol extends BaseUsuarioRol
{
   public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

}