# default values

all:
  default_name_project: Extranet Sectorial AMAT
  default_from_email: alertas@extranet.amat.es
  default_from_email_comunicados: comunicados@extranet.amat.es
  key_aplication: 12345678901234567890123456789012
  
  # thumbnail default por si no se define el tamanio abajo
  thumbnail_normal_width_default:  250
  thumbnail_normal_height_default: 320

  # thumbnail cifras y datos
  thumbnail_web_original_width_cifras_datos:   500
  thumbnail_web_original_height_cifras_datos:  500
  thumbnail_web_small_width_cifras_datos:   120
  thumbnail_web_small_height_cifras_datos:  90
  thumbnail_web_width_cifras_datos:   250
  thumbnail_web_height_cifras_datos:  150
  thumbnail_small_width_cifras_datos:   80
  thumbnail_small_height_cifras_datos:  60
  thumbnail_normal_width_cifras_datos:  250
  thumbnail_normal_height_cifras_datos: 320

  # thumbnail actividades
  thumbnail_web_original_width_actividades:   500
  thumbnail_web_original_height_actividades:  500
  thumbnail_web_small_width_actividades:   184
  thumbnail_web_small_height_actividades:  56
  thumbnail_web_width_actividades:   120
  thumbnail_web_height_actividades:  120
  thumbnail_small_width_actividades:   80
  thumbnail_small_height_actividades:  60
  thumbnail_normal_width_actividades:  250
  thumbnail_normal_height_actividades: 320

  # thumbnail publicaciones
  thumbnail_web_original_width_publicaciones:   500
  thumbnail_web_original_height_publicaciones:  500
  thumbnail_web_small_width_publicaciones:   184
  thumbnail_web_small_height_publicaciones:  56
  thumbnail_web_width_publicaciones:   120
  thumbnail_web_height_publicaciones:  120
  thumbnail_small_width_publicaciones:   80
  thumbnail_small_height_publicaciones:  60
  thumbnail_normal_width_publicaciones:  250
  thumbnail_normal_height_publicaciones: 320
  
  # thumbnail noticias
  thumbnail_web_original_width_noticias:   500
  thumbnail_web_original_height_noticias:  500
  thumbnail_web_small_width_noticias:   184
  thumbnail_web_small_height_noticias:  56
  thumbnail_web_width_noticias:   120
  thumbnail_web_height_noticias:  120
  thumbnail_small_width_noticias:   80
  thumbnail_small_height_noticias:  60
  thumbnail_normal_width_noticias:  250
  thumbnail_normal_height_noticias: 320

  # thumbnail eventos
  thumbnail_web_original_width_eventos:   500
  thumbnail_web_original_height_eventos:  500
  thumbnail_web_small_width_eventos:   184
  thumbnail_web_small_height_eventos:  56
  thumbnail_web_width_eventos:   120
  thumbnail_web_height_eventos:  120
  thumbnail_small_width_eventos:   80
  thumbnail_small_height_eventos:  60
  thumbnail_normal_width_eventos:  250
  thumbnail_normal_height_eventos: 320

  # thumbnail Tipos Comunicados
  thumbnail_small_width_tipo_comunicado:   300
  thumbnail_small_height_tipo_comunicado:  26
  thumbnail_normal_width_tipo_comunicado:  800
  thumbnail_normal_height_tipo_comunicado: 80
