all:
  is_secure:   off

delete:
  is_secure:   off
  credentials: [[ admin, superadmin ]]

editar:
  is_secure:   off
  credentials: [[ admin, superadmin ]]

nueva:
  is_secure:   off
  credentials: [[ admin, superadmin ]]
