<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaIniciativaTable extends Doctrine_Table
{
	public static  function getAll()
	{
		$q = Doctrine_Query::create()
		->from('CategoriaIniciativa')
		->where('deleted = 0 ');	
		
		return $q->execute();
	}

	
	
}