<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CircularTable extends DocumentacionTable
{
	public static function doSelectAllCategorias($tabla)
	{
		$q = Doctrine_Query::create();

		$q->from($tabla);
		$q->where('deleted = 0');
		$q->orderBy('nombre ASC');

		$categorias = $q->execute();

		return $categorias;
	}
	
	public static function getFechasCategorias()
	{
		$r = Doctrine_Query::create()
		->select('MIN(YEAR(fecha)) AS min_year, MAX(YEAR(fecha)) AS max_year')
		->from('Circular')->where('deleted = 0');
		
//	    echo '<pre>';
//	    print_r($r->fetchOne());
//	    echo '</pre>';
//		die();
		return $r->fetchOne();
	}

         public static function getAll()
       {
            $q=Doctrine_Query::create()
           ->from('Circular')
           ->where('deleted = 0');

           return $q->execute();

       }
	
	
}