<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaIniciativa extends BaseSubCategoriaIniciativa
{

	public function __toString()
	{
		return $this->nombre;
	}
	
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public static function getArraySubCategoria($id)
	{
		if($id == 0)
		{
			$subcategoria = SubCategoriaIniciativaTable::getAll();
		}
		else 
		{
			$subcategoria = SubCategoriaIniciativaTable::getSubcategiriaBycategoria($id);
		}	
		
		$arraysubcategoria = array('0'=>'--seleccionar--');
		
		foreach ($subcategoria as $c)
		{
			
			$arraysubcategoria[$c->getId()] = $c->getNombre();
			
		}
		
		return $arraysubcategoria;
	}
	
}