<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaAcuerdoTable extends Doctrine_Table
{

    public static function getSubcategiriaBycategoria($id)
	{
	   $q = Doctrine_Query::create()
	   ->from('SubCategoriaAcuerdo')
	   ->where('categoria_acuerdo_id = '.$id)
	   ->andWhere('deleted = 0');
	   
	   return $q->execute();
	   
	}


}