<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioAplicacionExterna extends BaseUsuarioAplicacionExterna
{
	public function generarSalt()
	{
		if (!$this->salt) 
		{
			$this->number_access = 1;
		}
		else 
		{
			$this->number_access = $this->number_access + 1;
		}
		

		
		$this->salt = md5('-'.$this->number_access.'-'.$this->login.'-'.$this->getAplicacionExterna()->getUrl().'-');

	}
}