<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AplicacionRol extends BaseAplicacionRol
{

	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	
	public static function getArraPerfilAplicacionAccionBYusuario($idUsuario)
	{ 
		$arrayRetorno = array();
		
		$perfiles = UsuarioRol::getRepository()->getRolesByUser($idUsuario,1);
		
		foreach ( $perfiles as $K=>$p)
		{ 
			$arrayRetorno[$K]['perfil'] = $p ;
			$arrayRetorno[$K]['apliacio'] = AplicacionRol::getRepository()->getAplicacionByRol($K);
		}
		
		return $arrayRetorno;
		
	}
}