<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoCT extends BaseArchivoCT
{

	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	
}