<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoDG extends BaseArchivoDG
{
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	
}