<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Circular extends BaseCircular
{
	public static function getRanfoDEfechas($modulo = '')
	{
		if($modulo == 'circulares')
		{
		   $RangodeA = CircularTable::getFechasCategorias();
		}
		if($modulo == 'iniciativas')
		{
		   $RangodeA = IniciativaTable::getFechasCategorias();	
		}
		if($modulo == 'normativas')
		{
		  $RangodeA = NormativaTable::getFechasCategorias();
		}
		
        $min = $RangodeA->getMinYear();
        $max = $RangodeA->getMaxYear();
        $arrayfecha = array();
		$arrayfecha[$min]= $min;
		if($min < $max)
		{
			do
			{
				$year = $min++;
				$arrayfecha[$year]= $year;
			}
			while ($min <= $max );
			
		}
		
		
		return $arrayfecha;
		
	}
	
	

}