<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenidoNotificacionTable extends Doctrine_Table
{
	public static function getOneByAccionAndEntidad($accion = '', $entidad = '')
	{
		$q = Doctrine_Query::create();
		$q->from('ContenidoNotificacion cn');
		$q->where('cn.deleted = 0');
		if($accion != '' && $entidad!='')
		{
			$q->addWhere('cn.accion=\'' . $accion . '\'');
			$q->addWhere('cn.entidad=\'' . $entidad . '\'');
			
	        $contenidoNofiticacion = $q->fetchOne();
		}
		else 
		{
			$contenidoNofiticacion = $q->execute();
		}
		
		
		return $contenidoNofiticacion;
	}
	
	
}