<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenidoNotificacion extends BaseContenidoNotificacion
{
   public function __toString()
	{
		return $this->titulo;
	}
	
	
}