<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Envios extends BaseEnvios
{

	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}

	public function saveEnvios($idenvios, $idusuario, $idmessage)
	{
		$this->setEnvioId($idenvios);
		$this->setUsuarioId($idusuario);
		$this->setMessageId($idmessage);
		$this->save();	
	}
	
	
}