<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mutua extends BaseMutua
{
	public function __toString()
	{
		return $this->nombre;
	}
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	
	public static function getArrayMutuas()
	{
		$ArrayMutuas = array(''=>'--seleccionar--','0'=>'Sin Mutua');
		$ModelosMutuas = MutuaTable::getAllMutuas();
		
		foreach ($ModelosMutuas AS $m)
		{
			$ArrayMutuas[$m->getId()] = $m->getNombre();
		}
		
		return $ArrayMutuas;
	}

        public static function getArrayMutuasNoiticias()
	{
                sfLoader::loadHelpers('Text');
		$ArrayMutuas = array(''=>'--seleccionar--','0'=>'Sin Mutua');
		$ModelosMutuas = MutuaTable::getAllMutuas();

		foreach ($ModelosMutuas AS $m)
		{
			$ArrayMutuas[$m->getId()] = truncate_text($m->getNombre(),30);
		}

		return $ArrayMutuas;
	}



}