<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Normativa extends BaseNormativa
{
	public function eliminarDocumento(){
		@unlink(sfConfig::get('sf_upload_dir').'/normativas/docs/'.$this->getDocumento());
	}
}