<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NormativaTable extends DocumentacionTable
{

	public static function getFechasCategorias()
	{
		$r = Doctrine_Query::create()
		->select('MIN(YEAR(fecha)) AS min_year, MAX(YEAR(fecha)) AS max_year')
		->from('Normativa')->where('deleted = 0');
		
//	    echo '<pre>';
//	    print_r($r->fetchOne());
//	    echo '</pre>';
//		die();
		return $r->fetchOne();
	}
}