<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticiaTable extends Doctrine_Table
{
	public static function getAll($perPage, $currentPage)
	{
		$pager = new sfDoctrinePager('Noticia', $perPage);
		$pager->getQuery()->from('Noticia')->where('deleted=0');
		$pager->setPage($currentPage);
		$pager->init();
		
		return $pager;
	}
	
	public static function getUltimasNoticias($limit=null,$rol='')
	{
		$q = Doctrine_Query::create();
		$q->from('Noticia n');
		$q->Where("n.estado = 'publicado'");
		if($rol !='')
		{
			$q->andWhere('n.deleted=0');
		}
		else 
		{
			$q->andWhere("n.deleted=0  AND n.ambito != 'web' AND n.fecha_publicacion <= NOW() AND (n.fecha_caducidad >= NOW() OR n.fecha_caducidad IS NULL ) ");
		}	
		$q->andWhere("n.destacada = 1");
		$q->orderBy('n.id DESC');
		if($limit) $q->limit($limit);
		

		
			
		$notificaciones = $q->execute();
		
		return $notificaciones;
	}
	
	public static  function getNoticiasCaducas()
	{
		$q = Doctrine_Query::create()
		->from('Noticia')
		->where('deleted=0 AND (fecha_caducidad <= NOW())');
		
		return  $q->execute();
	}
}