<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Organismo extends BaseOrganismo
{
	public function __toString()
	{
		return $this->nombre;
	}
	public static function getRepository()
	{
		return Doctrine::getTable(__CLASS__);
	}
	public function getUsusriosMiOrganismo($usuarioId)
	{
		$s = Doctrine_Query::create();
		$s->select('u.*');
		$s->from('Usuario u');
		$s->leftJoin('u.UsuarioOrganismo uo');
		$s->where('uo.organismo_id = '.$this->getId() );
                $s->andWhere('u.deleted = 0 AND u.activo = 1');
		$s->andWhere('u.id != '.$usuarioId);
		
		$usuarios = $s->execute();
		
		return $usuarios;
	}
	public static  function IdDeOrganismo($id_usuario='',$misuser='')
	{
                if($id_usuario)
                {
                    $consejos = OrganismoTable::getOrganismoBysuer($id_usuario);
                }
                else
                {
                    $consejos = OrganismoTable::getOrganismoBysuer();
                }
		
		if(count($consejos)>0)
		{
			if($misuser=='')
			{
				$armado =" AND am.entidad IN (";
				$base = 'Organismo_';
			}	
			else 
			{
				$armado ="(";
				$base = '';
			}
			$rt = 0;
			foreach ( $consejos AS $gruposid )
			{ 
				$rt++;
				if($rt != count($consejos))
				{
				  $armado .= "'".$base.$gruposid->getId()."',";
				}
				else 
				{
				  $armado .= "'".$base.$gruposid->getId()."')";
				}
				
				
			}
		}
		else 
		{
			$armado='(0)';
		}
		
	   return 	$armado;
	}
        public static function getUrlOrganismos($organismo,$type = '')
        {
            $request =sfContext::getInstance();
            $user = $request->getUser()->getAttribute('userId');
            $organismosArray= array('0'=>'','1'=>'');
            $organismos = OrganismoTable::getOrganismosByid($organismo);
            $categoriaId = $organismos->getCategoriaOrganismoId();
            $organismosArray['1'] = SubCategoriaOrganismoTable::doSelectByCategoria($categoriaId);
            $subcategoriaID = $organismos->getSubcategoriaOrganismoId();
            $organismosArray['0'] = OrganismoTable::doSelectByOrganismoa($subcategoriaID,$user);
            if($type == ''){
                return 'documentacion_organismo[categoria_organismo_id]='.$categoriaId.'&documentacion_organismo[subcategoria_organismo_id]='.$organismos->getSubcategoriaOrganismoId().'&documentacion_organismo[organismo_id]='.$organismo;
            }else{
                return $organismosArray;
            }

        }

}