<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaOrganismoTable extends Doctrine_Table
{
	public static function doSelectByCategoria($categoria)
	{
		if (empty($categoria)) {return false;}

		$q = Doctrine_Query::create();

		$q->from('SubCategoriaOrganismo');
		$q->where('deleted = 0');
		$q->addWhere('categoria_organismo_id = ' . $categoria);
		$q->orderBy('nombre ASC');

		$subcategoria = $q->execute();

		return $subcategoria;
	}
	
	public static function getAllsubcategoriaOrg()
	{
		$s = Doctrine_Query::create()->from('SubCategoriaOrganismo');
		$retorno = $s->execute();
		return $retorno;
	}
	
	public static function getSubcategoria($id_subcategoria)
	{
		$r = Doctrine_Query::create()
		->from('SubCategoriaOrganismo')
		->where('id = '.$id_subcategoria);
		$consulta = $r->fetchOne();
		
		return $consulta; 
	}
}