default:
  http_metas:
    content-type: text/html

  metas:
    title:         Extranet
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow

  stylesheets:     [styles.css, superfish.css, /css/smoothness/jquery-ui-1.7.2.custom.css]
  #SpryAssets/SpryMenuBarHorizontal.css, SpryAssets/SpryTooltip.css, 

  javascripts:     [jquery-1.3.2.min.js, jquery-ui-1.7.2.custom.min.js, %SF_PROTOTYPE_WEB_DIR%/js/prototype, SpryAssets/SpryMenuBar.js, SpryAssets/SpryTooltip.js, superfish/superfish.js, superfish/hoverIntent.js, superfish/inicio.js]
  #superfish/jquery-1.2.6.min.js, 

  has_layout:      on
  layout:          layout
